// ReactProject/src/components/Login.tsx
import React from 'react';

export default function Login({ navigate }: { navigate: (view: string) => void }) {
  return (
    <div className="flex flex-col min-h-full bg-white relative overflow-hidden">
      {/* Background Decoration */}
      <div className="absolute top-0 left-0 w-full h-64 bg-gradient-to-b from-[#A60000]/10 to-transparent -z-10" />
      <div className="absolute -top-24 -right-24 w-64 h-64 bg-[#A60000]/5 rounded-full blur-3xl -z-10" />
      <div className="absolute top-32 -left-24 w-48 h-48 bg-[#A60000]/5 rounded-full blur-2xl -z-10" />

      <div className="flex-1 flex flex-col items-center justify-center px-8">
        {/* Logo */}
        <div className="w-24 h-24 bg-[#A60000] rounded-3xl flex items-center justify-center text-white font-bold text-4xl shadow-xl shadow-[#A60000]/20 mb-6">
          潮
        </div>
        
        {/* App Name & Slogan */}
        <h1 className="text-3xl font-bold text-gray-800 mb-2 tracking-wider">潮汕·英歌行</h1>
        <p className="text-sm text-gray-500 mb-16 tracking-widest">探索最地道的潮汕风情</p>

        {/* Login Button */}
        <button 
          onClick={() => navigate('home')}
          className="w-full bg-[#A60000] text-white font-bold text-lg py-4 rounded-full shadow-lg shadow-[#A60000]/30 active:scale-95 transition-all flex items-center justify-center space-x-2"
        >
          <span>快捷登录</span>
        </button>

        {/* User Agreement */}
        <div className="mt-6 flex items-center justify-center space-x-2 text-xs text-gray-400">
          <input type="checkbox" className="w-3 h-3 accent-[#A60000] rounded-sm" defaultChecked />
          <span>我已阅读并同意</span>
          <span className="text-[#A60000] cursor-pointer">《用户协议》</span>
          <span>和</span>
          <span className="text-[#A60000] cursor-pointer">《隐私政策》</span>
        </div>
      </div>
    </div>
  );
}

// src/pages/login/index.vue
<template>
  <view class="login-page">
    <view class="bg-gradient" />
    <view class="bg-circle-right" />
    <view class="bg-circle-left" />

    <view class="flex-1 flex flex-col items-center justify-center px-8">
      <view class="logo-box">
        <text class="logo-text">潮</text>
      </view>

      <text class="app-title">潮汕·英歌行</text>
      <text class="app-slogan">探索最地道的潮汕风情</text>

      <view class="w-full mt-16" @click="handleLogin">
        <view class="login-btn">
          <text class="login-btn-text">快捷登录</text>
        </view>
      </view>

      <view class="mt-6 flex items-center justify-center text-xs">
        <checkbox
          :checked="agreed"
          color="#A60000"
          style="transform: scale(0.6)"
          @click="agreed = !agreed"
        />
        <text class="text-gray-400">我已阅读并同意</text>
        <text class="link-text">《用户协议》</text>
        <text class="text-gray-400">和</text>
        <text class="link-text">《隐私政策》</text>
      </view>
    </view>
  </view>
</template>

<script setup>
const agreed = ref(true)

const handleLogin = () => {
  if (!agreed.value) {
    uni.showToast({ title: '请先同意用户协议', icon: 'none' })
    return
  }
  uni.switchTab({ url: '/pages/home/index' })
}
</script>

<style scoped lang="scss">
.login-page {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  background: #ffffff;
  position: relative;
  overflow: hidden;
}

.bg-gradient {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 512rpx;
  background: linear-gradient(to bottom, rgba(166, 0, 0, 0.1), transparent);
  z-index: 0;
}

.bg-circle-right {
  position: absolute;
  top: -192rpx;
  right: -192rpx;
  width: 512rpx;
  height: 512rpx;
  background: rgba(166, 0, 0, 0.05);
  border-radius: 50%;
  filter: blur(48px);
  z-index: 0;
}

.bg-circle-left {
  position: absolute;
  top: 256rpx;
  left: -192rpx;
  width: 384rpx;
  height: 384rpx;
  background: rgba(166, 0, 0, 0.05);
  border-radius: 50%;
  filter: blur(32px);
  z-index: 0;
}

.logo-box {
  width: 192rpx;
  height: 192rpx;
  background: #a60000;
  border-radius: 48rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-bottom: 48rpx;
  box-shadow: 0 20rpx 40rpx rgba(166, 0, 0, 0.2);
}

.logo-text {
  color: #ffffff;
  font-weight: bold;
  font-size: 72rpx;
}

.app-title {
  font-size: 60rpx;
  font-weight: bold;
  color: #1f2937;
  margin-bottom: 16rpx;
  letter-spacing: 4rpx;
}

.app-slogan {
  font-size: 28rpx;
  color: #6b7280;
  letter-spacing: 6rpx;
}

.login-btn {
  width: 100%;
  background: #a60000;
  border-radius: 100rpx;
  padding: 32rpx 0;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 16rpx 32rpx rgba(166, 0, 0, 0.3);
}

.login-btn:active {
  transform: scale(0.95);
}

.login-btn-text {
  color: #ffffff;
  font-weight: bold;
  font-size: 34rpx;
}

.link-text {
  color: #a60000;
  font-size: 24rpx;
}
</style>
