// src/pages/chat/index.vue
<template>
  <view class="page">
    <!-- Header -->
    <view class="header">
      <text class="back-icon" @click="goBack">←</text>
      <text class="header-title">在线客服</text>
      <view class="header-spacer" />
    </view>

    <!-- Chat messages -->
    <scroll-view scroll-y class="chat-area" :scroll-into-view="scrollTarget">
      <view class="messages">
        <view
          v-for="msg in messages"
          :key="msg.id"
          :class="['msg-row', msg.type === 'user' ? 'msg-right' : 'msg-left']"
        >
          <view :class="['msg-bubble', msg.type === 'user' ? 'bubble-user' : 'bubble-system']">
            <text class="msg-text">{{ msg.text }}</text>
            <text :class="['msg-time', msg.type === 'user' ? 'time-user' : 'time-system']">{{ msg.time }}</text>
          </view>
        </view>
        <view :id="'msg-bottom'" />
      </view>
    </scroll-view>

    <!-- Input -->
    <view class="input-bar">
      <input
        type="text"
        v-model="inputText"
        placeholder="请输入您的问题..."
        class="chat-input"
        confirm-type="send"
        @confirm="handleSend"
      />
      <view class="send-btn" @click="handleSend">
        <text class="send-icon">➤</text>
      </view>
    </view>
  </view>
</template>

<script setup>
const messages = ref([
  { id: 1, type: 'system', text: '欢迎来到潮汕英歌行在线客服，请问有什么可以帮您？', time: '10:00' }
])
const inputText = ref('')
const scrollTarget = ref('')

const getCurrentTime = () => {
  const now = new Date()
  return `${now.getHours().toString().padStart(2, '0')}:${now.getMinutes().toString().padStart(2, '0')}`
}

const scrollToBottom = () => {
  nextTick(() => {
    scrollTarget.value = ''
    setTimeout(() => { scrollTarget.value = 'msg-bottom' }, 50)
  })
}

const handleSend = () => {
  const text = inputText.value.trim()
  if (!text) return

  messages.value.push({
    id: Date.now(),
    type: 'user',
    text,
    time: getCurrentTime()
  })
  inputText.value = ''
  scrollToBottom()

  setTimeout(() => {
    messages.value.push({
      id: Date.now() + 1,
      type: 'system',
      text: '客服代表已收到您的消息，正在为您处理，请稍候...',
      time: getCurrentTime()
    })
    scrollToBottom()
  }, 1000)
}

const goBack = () => uni.navigateBack()
</script>

<style scoped lang="scss">
.page {
  height: 100vh;
  display: flex;
  flex-direction: column;
  background: #f9fafb;
}
.header {
  display: flex;
  align-items: center;
  padding: 80rpx 30rpx 24rpx;
  background: #fff;
  border-bottom: 1rpx solid #f3f4f6;
  flex-shrink: 0;
}
.back-icon {
  font-size: 40rpx;
  color: #1f2937;
  width: 60rpx;
}
.header-title {
  flex: 1;
  text-align: center;
  font-size: 34rpx;
  font-weight: bold;
  color: #1f2937;
}
.header-spacer { width: 60rpx; }
.chat-area {
  flex: 1;
  overflow: hidden;
}
.messages {
  padding: 24rpx;
}
.msg-row {
  display: flex;
  margin-bottom: 24rpx;
}
.msg-right {
  justify-content: flex-end;
}
.msg-left {
  justify-content: flex-start;
}
.msg-bubble {
  max-width: 75%;
  padding: 24rpx;
  border-radius: 28rpx;
}
.bubble-user {
  background: #A60000;
  border-top-right-radius: 6rpx;
}
.bubble-system {
  background: #fff;
  border: 1rpx solid #f3f4f6;
  border-top-left-radius: 6rpx;
}
.msg-text {
  font-size: 28rpx;
  line-height: 1.5;
}
.bubble-user .msg-text {
  color: #fff;
}
.bubble-system .msg-text {
  color: #1f2937;
}
.msg-time {
  font-size: 20rpx;
  margin-top: 8rpx;
  text-align: right;
  display: block;
}
.time-user {
  color: rgba(255,255,255,0.7);
}
.time-system {
  color: #9ca3af;
}
.input-bar {
  display: flex;
  align-items: center;
  padding: 16rpx 24rpx;
  background: #fff;
  border-top: 1rpx solid #f3f4f6;
  flex-shrink: 0;
  padding-bottom: calc(16rpx + env(safe-area-inset-bottom));
}
.chat-input {
  flex: 1;
  background: #f3f4f6;
  border-radius: 999rpx;
  padding: 18rpx 28rpx;
  font-size: 28rpx;
}
.send-btn {
  width: 72rpx;
  height: 72rpx;
  background: #A60000;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin-left: 16rpx;
  flex-shrink: 0;
}
.send-icon {
  color: #fff;
  font-size: 30rpx;
}
</style>

// ReactProject/src/components/Chat.tsx
import React, { useState } from 'react';
import { ChevronLeft, Send } from 'lucide-react';

export default function Chat({ goBack }: { goBack: () => void }) {
  const [messages, setMessages] = useState([
    { id: 1, type: 'system', text: '欢迎来到潮汕英歌行在线客服，请问有什么可以帮您？', time: '10:00' }
  ]);
  const [input, setInput] = useState('');

  const handleSend = () => {
    if (!input.trim()) return;
    
    const newMsg = {
      id: Date.now(),
      type: 'user',
      text: input,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    
    setMessages([...messages, newMsg]);
    setInput('');
    
    // Mock reply
    setTimeout(() => {
      setMessages(prev => [...prev, {
        id: Date.now() + 1,
        type: 'system',
        text: '客服代表已收到您的消息，正在为您处理，请稍候...',
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      }]);
    }, 1000);
  };

  return (
    <div className="flex flex-col h-full bg-gray-50">
      <div className="bg-white pt-12 pb-4 px-4 sticky top-0 z-40 flex items-center border-b border-gray-100 shadow-sm">
        <ChevronLeft className="w-6 h-6 text-gray-800 cursor-pointer" onClick={goBack} />
        <h1 className="flex-1 text-center text-lg font-bold text-gray-800 pr-6">在线客服</h1>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4 pb-20">
        {messages.map(msg => (
          <div key={msg.id} className={`flex ${msg.type === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`max-w-[75%] rounded-2xl p-3 ${msg.type === 'user' ? 'bg-[#A60000] text-white rounded-tr-sm' : 'bg-white border border-gray-100 text-gray-800 rounded-tl-sm shadow-sm'}`}>
              <p className="text-sm leading-relaxed">{msg.text}</p>
              <p className={`text-[10px] mt-1 text-right ${msg.type === 'user' ? 'text-white/70' : 'text-gray-400'}`}>{msg.time}</p>
            </div>
          </div>
        ))}
      </div>

      <div className="fixed bottom-0 w-full max-w-md bg-white border-t border-gray-100 p-3 flex items-center space-x-2 z-50">
        <input 
          type="text" 
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyPress={(e) => e.key === 'Enter' && handleSend()}
          placeholder="请输入您的问题..." 
          className="flex-1 bg-gray-50 border border-gray-200 rounded-full px-4 py-2.5 text-sm focus:outline-none focus:border-[#A60000]"
        />
        <button 
          onClick={handleSend}
          className="w-10 h-10 bg-[#A60000] rounded-full flex items-center justify-center text-white flex-shrink-0 active:scale-95 transition-transform"
        >
          <Send className="w-4 h-4 ml-[-2px]" />
        </button>
      </div>
    </div>
  );
}
