// src/pages/guide-booking/index.vue
<template>
  <view class="page">
    <!-- Header -->
    <view class="header">
      <view class="back-btn" @click="goBack">
        <text class="back-arrow">←</text>
      </view>
      <text class="header-title">预约导游</text>
      <view class="header-placeholder" />
    </view>

    <!-- Guide Info Card -->
    <view class="guide-card">
      <image class="guide-avatar" :src="params.img || 'https://picsum.photos/seed/avatar/200/200'" mode="aspectFill" />
      <view class="guide-info">
        <text class="guide-name">{{ params.name || '导游' }}</text>
        <text class="guide-label">专业认证导游</text>
      </view>
    </view>

    <!-- Booking Type -->
    <view class="section">
      <text class="section-title">预约类型</text>
      <view class="type-cards">
        <view
          class="type-card"
          :class="{ 'type-active': bookingType === 'fullday' }"
          @click="bookingType = 'fullday'"
        >
          <text class="type-name">全天预约</text>
          <text class="type-price">¥300<text class="type-unit">/天</text></text>
        </view>
        <view
          class="type-card"
          :class="{ 'type-active': bookingType === 'hourly' }"
          @click="bookingType = 'hourly'"
        >
          <text class="type-name">按小时预约</text>
          <text class="type-price">¥50<text class="type-unit">/小时</text></text>
        </view>
      </view>
    </view>

    <!-- Date Selection -->
    <view class="section">
      <text class="section-title">选择日期</text>
      <scroll-view scroll-x class="date-scroll">
        <view class="date-row">
          <view
            class="date-item"
            :class="{ 'date-active': selectedDate === idx }"
            v-for="(day, idx) in dateOptions"
            :key="idx"
            @click="selectedDate = idx"
          >
            <text class="date-label">{{ day.label }}</text>
            <text class="date-value">{{ day.date }}</text>
          </view>
        </view>
      </scroll-view>
    </view>

    <!-- Time Slot Grid (hourly only) -->
    <view class="section" v-if="bookingType === 'hourly'">
      <text class="section-title">选择时间段</text>
      <view class="time-grid">
        <view
          class="time-slot"
          :class="{ 'time-selected': selectedHours.includes(idx) }"
          v-for="(slot, idx) in timeSlots"
          :key="idx"
          @click="toggleHour(idx)"
        >
          <text class="time-text">{{ slot }}</text>
        </view>
      </view>
    </view>

    <!-- Spacer for bottom bar -->
    <view class="bottom-spacer" />

    <!-- Bottom Bar -->
    <view class="bottom-bar">
      <view class="price-info">
        <text class="price-label">合计</text>
        <text class="price-amount">¥{{ totalPrice }}</text>
      </view>
      <view class="confirm-btn" @click="confirmBooking">
        <text class="confirm-btn-text">确认预约</text>
      </view>
    </view>
  </view>
</template>

<script setup>
import { onLoad } from '@dcloudio/uni-app'
import { useNavStore } from '@/store/useNavStore'

const navStore = useNavStore()
const params = ref({})

const bookingType = ref('fullday')
const selectedDate = ref(0)
const selectedHours = ref([])

const dateOptions = [
  { label: '今天', date: '03-23' },
  { label: '明天', date: '03-24' },
  { label: '后天', date: '03-25' },
]

const timeSlots = [
  '09:00-10:00',
  '10:00-11:00',
  '11:00-12:00',
  '12:00-13:00',
  '13:00-14:00',
  '14:00-15:00',
  '15:00-16:00',
  '16:00-17:00',
  '17:00-18:00',
  '18:00-19:00',
  '19:00-20:00',
  '20:00-21:00',
  '21:00-22:00',
]

const totalPrice = computed(() => {
  if (bookingType.value === 'fullday') return 300
  return selectedHours.value.length * 50
})

const toggleHour = (idx) => {
  const i = selectedHours.value.indexOf(idx)
  if (i === -1) {
    selectedHours.value.push(idx)
  } else {
    selectedHours.value.splice(i, 1)
  }
}

const confirmBooking = () => {
  if (bookingType.value === 'hourly' && selectedHours.value.length === 0) {
    uni.showToast({ title: '请选择时间段', icon: 'none' })
    return
  }
  uni.showToast({ title: '预约成功！', icon: 'success' })
}

onLoad(() => {
  params.value = navStore.params || {}
})

const goBack = () => {
  uni.navigateBack()
}
</script>

<style scoped lang="scss">
.page {
  min-height: 100vh;
  background: #f5f5f5;
}

.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 30rpx;
  height: 88rpx;
  background: #ffffff;
  position: sticky;
  top: 0;
  z-index: 100;
  padding-top: env(safe-area-inset-top);
}

.back-btn {
  width: 60rpx;
  height: 60rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}

.back-arrow {
  font-size: 36rpx;
  color: #333333;
  font-weight: bold;
}

.header-title {
  font-size: 34rpx;
  font-weight: bold;
  color: #1a1a1a;
}

.header-placeholder {
  width: 60rpx;
}

.guide-card {
  display: flex;
  align-items: center;
  gap: 24rpx;
  margin: 20rpx 30rpx;
  padding: 30rpx;
  background: #ffffff;
  border-radius: 16rpx;
  box-shadow: 0 4rpx 16rpx rgba(0, 0, 0, 0.06);
}

.guide-avatar {
  width: 100rpx;
  height: 100rpx;
  border-radius: 50%;
}

.guide-info {
  display: flex;
  flex-direction: column;
  gap: 8rpx;
}

.guide-name {
  font-size: 32rpx;
  font-weight: bold;
  color: #1a1a1a;
}

.guide-label {
  font-size: 24rpx;
  color: #a60000;
}

.section {
  margin: 20rpx 30rpx;
}

.section-title {
  display: block;
  font-size: 30rpx;
  font-weight: bold;
  color: #333333;
  margin-bottom: 20rpx;
}

.type-cards {
  display: flex;
  gap: 20rpx;
}

.type-card {
  flex: 1;
  padding: 30rpx 20rpx;
  background: #ffffff;
  border: 2rpx solid #e0e0e0;
  border-radius: 16rpx;
  text-align: center;
  transition: all 0.2s;
}

.type-active {
  border-color: #a60000;
  background: rgba(166, 0, 0, 0.04);
}

.type-name {
  display: block;
  font-size: 28rpx;
  color: #333333;
  margin-bottom: 12rpx;
  font-weight: bold;
}

.type-price {
  font-size: 36rpx;
  color: #a60000;
  font-weight: bold;
}

.type-unit {
  font-size: 22rpx;
  color: #999999;
  font-weight: normal;
}

.date-scroll {
  white-space: nowrap;
}

.date-row {
  display: flex;
  gap: 16rpx;
}

.date-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 20rpx 36rpx;
  background: #ffffff;
  border: 2rpx solid #e0e0e0;
  border-radius: 12rpx;
  flex-shrink: 0;
}

.date-active {
  border-color: #a60000;
  background: rgba(166, 0, 0, 0.04);
}

.date-label {
  font-size: 26rpx;
  color: #333333;
  font-weight: bold;
}

.date-value {
  font-size: 24rpx;
  color: #999999;
  margin-top: 4rpx;
}

.date-active .date-label {
  color: #a60000;
}

.date-active .date-value {
  color: #a60000;
}

.time-grid {
  display: flex;
  flex-wrap: wrap;
  gap: 16rpx;
}

.time-slot {
  width: calc(33.33% - 12rpx);
  padding: 20rpx 0;
  background: #ffffff;
  border: 2rpx solid #e0e0e0;
  border-radius: 12rpx;
  text-align: center;
}

.time-selected {
  border-color: #a60000;
  background: #a60000;
}

.time-text {
  font-size: 24rpx;
  color: #333333;
}

.time-selected .time-text {
  color: #ffffff;
}

.bottom-spacer {
  height: 160rpx;
}

.bottom-bar {
  position: fixed;
  bottom: 0;
  left: 0;
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20rpx 30rpx;
  padding-bottom: calc(20rpx + env(safe-area-inset-bottom));
  background: #ffffff;
  box-shadow: 0 -2rpx 12rpx rgba(0, 0, 0, 0.06);
  z-index: 100;
  box-sizing: border-box;
}

.price-info {
  display: flex;
  align-items: baseline;
  gap: 8rpx;
}

.price-label {
  font-size: 26rpx;
  color: #666666;
}

.price-amount {
  font-size: 40rpx;
  font-weight: bold;
  color: #a60000;
}

.confirm-btn {
  padding: 0 60rpx;
  height: 80rpx;
  background: #a60000;
  border-radius: 40rpx;
  display: flex;
  align-items: center;
  justify-content: center;
}

.confirm-btn-text {
  color: #ffffff;
  font-size: 30rpx;
  font-weight: bold;
}
</style>

// ReactProject/src/components/GuideBooking.tsx
import React, { useState } from 'react';
import { ChevronLeft, Calendar, Clock } from 'lucide-react';

export default function GuideBooking({ params, goBack }: { params: any, goBack: () => void }) {
  const [bookingType, setBookingType] = useState<'full' | 'hourly'>('full');
  const [selectedDate, setSelectedDate] = useState('03-23');
  const [selectedHours, setSelectedHours] = useState<string[]>([]);

  const toggleHour = (hour: string) => {
    if (selectedHours.includes(hour)) {
      setSelectedHours(selectedHours.filter(h => h !== hour));
    } else {
      setSelectedHours([...selectedHours, hour]);
    }
  };

  const dates = [
    { date: '03-23', label: '今天' },
    { date: '03-24', label: '明天' },
    { date: '03-25', label: '后天' },
  ];

  const hours = [
    '09:00-10:00', '10:00-11:00', '11:00-12:00', '12:00-13:00',
    '14:00-15:00', '15:00-16:00', '16:00-17:00', '17:00-18:00',
    '19:00-20:00', '20:00-21:00', '21:00-22:00'
  ];

  return (
    <div className="flex flex-col min-h-full bg-gray-50 pb-20">
      {/* Header */}
      <div className="bg-white pt-12 pb-4 px-4 sticky top-0 z-40 flex items-center border-b border-gray-100">
        <ChevronLeft className="w-6 h-6 text-gray-800 cursor-pointer" onClick={goBack} />
        <h1 className="flex-1 text-center text-lg font-bold text-gray-800 pr-6">预约导游</h1>
      </div>

      <div className="p-4 space-y-6">
        {/* Guide Info */}
        <div className="bg-white p-4 rounded-xl shadow-sm flex items-center space-x-4">
          <img src={params?.img || "https://picsum.photos/seed/g1/100/100"} className="w-16 h-16 rounded-full object-cover" referrerPolicy="no-referrer" alt="Guide" />
          <div>
            <h2 className="font-bold text-gray-800">{params?.name || '导游'}</h2>
            <p className="text-xs text-gray-500 mt-1">请选择您的预约方式和时间</p>
          </div>
        </div>

        {/* Booking Type */}
        <div>
          <h3 className="font-bold text-gray-800 mb-3">预约方式</h3>
          <div className="grid grid-cols-2 gap-3">
            <div 
              onClick={() => setBookingType('full')}
              className={`border rounded-xl p-4 flex flex-col items-center justify-center cursor-pointer transition-colors ${bookingType === 'full' ? 'border-[#A60000] bg-red-50 text-[#A60000]' : 'border-gray-200 bg-white text-gray-600'}`}
            >
              <Calendar className="w-6 h-6 mb-2" />
              <span className="text-sm font-medium">全天预约</span>
              <span className="text-xs mt-1 opacity-80">¥300/天</span>
            </div>
            <div 
              onClick={() => setBookingType('hourly')}
              className={`border rounded-xl p-4 flex flex-col items-center justify-center cursor-pointer transition-colors ${bookingType === 'hourly' ? 'border-[#A60000] bg-red-50 text-[#A60000]' : 'border-gray-200 bg-white text-gray-600'}`}
            >
              <Clock className="w-6 h-6 mb-2" />
              <span className="text-sm font-medium">按小时预约</span>
              <span className="text-xs mt-1 opacity-80">¥50/小时</span>
            </div>
          </div>
        </div>

        {/* Date Selection */}
        <div>
          <h3 className="font-bold text-gray-800 mb-3">选择日期</h3>
          <div className="flex space-x-3 overflow-x-auto hide-scrollbar">
            {dates.map(d => (
              <div 
                key={d.date}
                onClick={() => setSelectedDate(d.date)}
                className={`flex-shrink-0 w-20 py-3 rounded-lg flex flex-col items-center justify-center cursor-pointer border ${selectedDate === d.date ? 'border-[#A60000] bg-[#A60000] text-white' : 'border-gray-200 bg-white text-gray-600'}`}
              >
                <span className="text-xs mb-1">{d.label}</span>
                <span className="text-sm font-bold">{d.date}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Hour Selection (Only if hourly) */}
        {bookingType === 'hourly' && (
          <div>
            <h3 className="font-bold text-gray-800 mb-3">选择时间段 (可多选)</h3>
            <div className="grid grid-cols-3 gap-2">
              {hours.map(h => {
                const isSelected = selectedHours.includes(h);
                return (
                  <div 
                    key={h}
                    onClick={() => toggleHour(h)}
                    className={`py-2 rounded border text-center text-xs cursor-pointer transition-colors ${isSelected ? 'border-[#A60000] bg-red-50 text-[#A60000]' : 'border-gray-200 bg-white text-gray-600'}`}
                  >
                    {h}
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>

      {/* Bottom Bar */}
      <div className="fixed bottom-0 w-full max-w-md bg-white border-t border-gray-100 p-3 flex justify-between items-center z-50">
        <div className="text-[#A60000] font-bold text-xl">
          ¥{bookingType === 'full' ? 300 : selectedHours.length * 50}
        </div>
        <button className="bg-[#A60000] text-white px-8 py-2.5 rounded-full font-medium shadow-md active:scale-95 transition-transform">
          确认预约
        </button>
      </div>
    </div>
  );
}
